spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        default_schema: app

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /course_manager

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
    by:
      fin:
        shop_manager: DEBUG
  file:
    name: logs/spring-boot-application.log
    path: logs